In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv(r"H:\datasets\ecommerce-sales.csv")

In [5]:
df.head(20)

,CID,TID,Gender,Age Group,Purchase Date,Product Category,Discount Availed,Discount Name,Discount Amount (INR),Gross Amount,Net Amount,Purchase Method,Location
0,943146,5876328741,Female,25-45,30/08/2023 20:27:08,Electronics,Yes,FESTIVE50,64.30,725.304000,661.004000,Credit Card,Ahmedabad
1,180079,1018503182,Male,25-45,23/02/2024 09:33:46,Electronics,Yes,SEASONALOFFER21,175.19,4638.991875,4463.801875,Credit Card,Bangalore
2,337580,3814082218,Other,60 and above,06/03/2022 09:09:50,Clothing,Yes,SEASONALOFFER21,211.54,1986.372575,1774.832575,Credit Card,Delhi
3,180333,1395204173,Other,60 and above,04/11/2020 04:41:57,Sports & Fitness,No,NaN,0.00,5695.612650,5695.612650,Debit Card,Delhi
4,447553,8009390577,Male,18-25,31/05/2022 17:00:32,Sports & Fitness,Yes,WELCOME5,439.92,2292.651500,1852.731500,Credit Card,Delhi
5,200614,3994452858,Male,18-25,12/07/2021 15:10:27,Clothing,Yes,FESTIVE50,127.01,3649.397400,3522.387400,Credit Card,Delhi
6,668787,9460023916,Male,25-45,08/10/2023 16:59:52,Electronics,No,NaN,0.00,5593.935600,5593.935600,PhonePe UPI,Delhi
7,933551,6877673032,Female,18-25,14/12/2022 20:13:45,Electronics,No,NaN,0.00,1901.796400,1901.796400,Credit Card,Delhi
8,414167,2841266620,Male,18-25,29/04/2020 09:10:46,Pet Care,No,NaN,0.00,3961.671000,3961.671000,Debit Card,Delhi
9,889269,1342270638,Other,60 and above,18/12/2023 19:04:02,Clothing,Yes,SAVE10,437.50,1497.350400,1059.850400,Credit Card,Bangalore
10,931578,5168806107,Other,25-45,09/12/2022 19:54:47,Clothing,No,NaN,0.00,7824.165300,7824.165300,Credit Card,Other
11,629298,2229511931,Other,45-60,02/11/2021 15:37:38,Electronics,No,NaN,0.00,988.172900,988.172900,Google Pay UPI,Chennai
12,665042,3754858574,Female,25-45,23/09/2020 02:22:00,Electronics,Yes,SEASONALOFFER21,97.88,3508.937775,3411.057775,Net Banking,Dehradun
13,570860,6791123870,Male,25-45,15/02/2020 05:51:55,Electronics,Yes,FESTIVE50,269.87,618.109800,348.239800,Cash on Delivery,Chennai
14,367541,9916932604,Other,18-25,26/09/2021 06:13:58,Home & Kitchen,Yes,NEWYEARS,268.70,560.960400,292.260400,Credit Card,Pune
15,143460,2441027824,Other,25-45,15/07/2022 09:26:34,Electronics,No,NaN,0.00,4996.110600,4996.110600,Debit Card,Delhi
16,573298,5515725036,Other,25-45,27/05/2023 19:38:50,Sports & Fitness,No,NaN,0.00,2729.748000,2729.748000,Net Banking,Ahmedabad
17,454101,6091881739,Male,under 18,12/04/2020 20:37:09,Electronics,Yes,NEWYEARS,368.53,457.317000,88.787000,Credit Card,Hyderabad
18,337178,6774128207,Other,18-25,20/02/2021 00:10:11,Home & Kitchen,Yes,SEASONALOFFER21,375.51,4141.638600,3766.128600,Credit Card,Ahmedabad
19,787512,9582806381,Male,18-25,17/03/2021 17:32:46,Books,No,NaN,0.00,1952.415300,1952.415300,Paytm UPI,Mumbai

In [6]:
df.shape

(55000, 13)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55000 entries, 0 to 54999
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   CID                    55000 non-null  int64
 1   TID                    55000 non-null  int64
 2   Gender                 55000 non-null  object
 3   Age Group              55000 non-null  object
 4   Purchase Date          55000 non-null  object
 5   Product Category       55000 non-null  object
 6   Discount Availed       55000 non-null  object
 7   Discount Name          27415 non-null  object
 8   Discount Amount (INR)  55000 non-null  float64
 9   Gross Amount           55000 non-null  float64
 10  Net Amount             55000 non-null  float64
 11  Purchase Method        55000 non-null  object
 12  Location               55000 non-null  object
dtypes: float64(3), int64(2), object(8)
memory usage: 5.5+ MB

In [8]:
print(df.dtypes)

CID                        int64
TID                        int64
Gender                    object
Age Group                 object
Purchase Date             object
Product Category          object
Discount Availed          object
Discount Name             object
Discount Amount (INR)    float64
Gross Amount             float64
Net Amount               float64
Purchase Method           object
Location                  object
dtype: object

In [9]:
df["Purchase Date"]=pd.to_datetime(df["Purchase Date"])

C:\Users\Arsalan Wani\AppData\Local\Temp\ipykernel_18528\457761688.py:1: UserWarning: Parsing dates in %d/%m/%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Purchase Date"]=pd.to_datetime(df["Purchase Date"])

In [10]:
print(df.isna().sum())

CID                          0
TID                          0
Gender                       0
Age Group                    0
Purchase Date                0
Product Category             0
Discount Availed             0
Discount Name            27585
Discount Amount (INR)        0
Gross Amount                 0
Net Amount                   0
Purchase Method              0
Location                     0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df["Discount Availed"].unique()

array(['Yes', 'No'], dtype=object)

In [13]:
df[(df["Discount Availed"]=="Yes")&(df["Discount Name"].isna())]

Empty DataFrame
Columns: [CID, TID, Gender, Age Group, Purchase Date, Product Category, Discount Availed, Discount Name, Discount Amount (INR), Gross Amount, Net Amount, Purchase Method, Location]
Index: []

In [14]:
df[(df["Discount Availed"]=="No")&(df["Discount Name"])]

Empty DataFrame
Columns: [CID, TID, Gender, Age Group, Purchase Date, Product Category, Discount Availed, Discount Name, Discount Amount (INR), Gross Amount, Net Amount, Purchase Method, Location]
Index: []

Discount Data Validation

Finding:
The Discount Name field is conditionally populated based on Discount Availed.
- Discount availed → discount name is present.
- No discount availed → discount name is missing.
- Both consistency checks returned 0 exceptions.

In [15]:
df["Gender"].value_counts()

Gender
Female    18454
Other     18450
Male      18096
Name: count, dtype: int64

In [16]:
df["Age Group"].value_counts()

Age Group
25-45           22010
18-25           16431
45-60           11104
under 18         2771
60 and above     2684
Name: count, dtype: int64

In [17]:
df["Age Group"].isna().sum()

np.int64(0)

In [18]:
df["Product Category"].value_counts()

Product Category
Electronics          16574
Clothing             10968
Beauty and Health     8332
Sports & Fitness      5557
Home & Kitchen        5489
Books                 2762
Other                 2171
Pet Care              1618
Toys & Games          1529
Name: count, dtype: int64

In [19]:
df["Purchase Method"].value_counts()

Purchase Method
Credit Card           22096
Debit Card            13809
Net Banking            5485
International Card     2815
Cash on Delivery       2768
PhonePe UPI            2683
Paytm UPI              2674
Google Pay UPI         2670
Name: count, dtype: int64

In [20]:
df["Location"].value_counts()

Location
Mumbai       11197
Delhi        10799
Bangalore     8249
Hyderabad     5545
Chennai       4368
Pune          3781
Ahmedabad     2785
Kolkata       2709
Jaipur        1678
Lucknow       1136
Other         1046
Varanasi       606
Dehradun       553
Srinagar       548
Name: count, dtype: int64

In [21]:
df.columns

Index(['CID', 'TID', 'Gender', 'Age Group', 'Purchase Date',
       'Product Category', 'Discount Availed', 'Discount Name',
       'Discount Amount (INR)', 'Gross Amount', 'Net Amount',
       'Purchase Method', 'Location'],
      dtype='object')

In [22]:
(df['Discount Amount (INR)']<0).sum()

np.int64(0)

In [23]:
(df["Gross Amount"]<0).sum()

np.int64(0)

In [24]:
(df["Net Amount"]<0).sum()

np.int64(613)

In [25]:
df[df["Net Amount"]<0][['Product Category', 'Discount Availed', 'Discount Name',
       'Discount Amount (INR)', 'Gross Amount', 'Net Amount',
       'Purchase Method']]

,Product Category,Discount Availed,Discount Name,Discount Amount (INR),Gross Amount,Net Amount,Purchase Method
311,Beauty and Health,Yes,NEWYEARS,469.58,279.258000,-190.322000,Debit Card
383,Electronics,Yes,NEWYEARS,358.58,204.886500,-153.693500,Debit Card
398,Home & Kitchen,Yes,WELCOME5,385.36,246.808100,-138.551900,Debit Card
489,Home & Kitchen,Yes,NEWYEARS,427.33,348.448275,-78.881725,Credit Card
564,Electronics,Yes,SAVE10,429.49,414.914325,-14.575675,Credit Card
...,...,...,...,...,...,...,...
54271,Electronics,Yes,SEASONALOFFER21,443.65,379.287000,-64.363000,Debit Card
54280,Home & Kitchen,Yes,SEASONALOFFER21,305.25,178.402875,-126.847125,Paytm UPI
54378,Books,Yes,SAVE10,212.69,185.241000,-27.449000,PhonePe UPI
54536,Electronics,Yes,FESTIVE50,492.84,216.315000,-276.525000,Google Pay UPI
54903,Clothing,Yes,SEASONALOFFER21,362.14,247.819000,-114.321000,Debit Card

In [26]:
(df[df["Net Amount"]<0]["Discount Amount (INR)"]>df[df["Net Amount"]<0]["Gross Amount"]).sum()

np.int64(613)

Data Quality Check:

613 records have a negative Net Amount. Further investigation showed that in all 613 records, the Discount Amount is greater than the Gross Amount, resulting in a negative Net Amount.

In [27]:
(df["Gross Amount"]-df["Discount Amount (INR)"]==df["Net Amount"]).sum()

np.int64(48375)

In [28]:
np.isclose(df["Gross Amount"]-df["Discount Amount (INR)"],df["Net Amount"]).sum()

np.int64(55000)

In [29]:
df[~np.isclose(df["Gross Amount"]-df["Discount Amount (INR)"],df["Net Amount"])]

Empty DataFrame
Columns: [CID, TID, Gender, Age Group, Purchase Date, Product Category, Discount Availed, Discount Name, Discount Amount (INR), Gross Amount, Net Amount, Purchase Method, Location]
Index: []

In [30]:
(df["Discount Amount (INR)"]/df["Gross Amount"]*100).describe()

count    55000.000000
mean         8.701620
std         20.260738
min          0.000000
25%          0.000000
50%          0.000000
75%          9.289298
max        345.314905
dtype: float64

In [31]:
(df[df["Net Amount"] < 0]["Discount Amount (INR)"] /
 df[df["Net Amount"] < 0]["Gross Amount"] * 100).describe()

count    613.000000
mean     147.248697
std       41.505388
min      100.098019
25%      114.931778
50%      137.990495
75%      167.002623
max      345.314905
dtype: float64

In [32]:
df[df["Net Amount"]<0]["Discount Name"].value_counts()

Discount Name
NEWYEARS           183
SEASONALOFFER21    148
SAVE10              96
WELCOME5            95
FESTIVE50           91
Name: count, dtype: int64

Finding: 
613 transactions have negative Net Amount because their Discount Amount exceeds their Gross Amount. The Net Amount calculation itself is consistent across the dataset.

In [33]:
df[["Discount Amount (INR)","Gross Amount","Net Amount"]].describe()

       Discount Amount (INR)  Gross Amount    Net Amount
count           55000.000000  55000.000000  55000.000000
mean              136.986796   3012.936606   2875.949810
std               165.375502   1718.431066   1726.127778
min                 0.000000    136.454325   -351.119775
25%                 0.000000   1562.111325   1429.551863
50%                 0.000000   2954.266150   2814.910875
75%               274.115000   4342.221675   4211.407838
max               500.000000   8394.825600   8394.825600

EXPLORATORY DATA ANALYSIS

In [37]:
df["Product Category"].value_counts()

Product Category
Electronics          16574
Clothing             10968
Beauty and Health     8332
Sports & Fitness      5557
Home & Kitchen        5489
Books                 2762
Other                 2171
Pet Care              1618
Toys & Games          1529
Name: count, dtype: int64

In [39]:
df.groupby("Product Category")["Net Amount"].sum().sort_values(ascending=False)

Product Category
Electronics          4.748257e+07
Clothing             3.122038e+07
Beauty and Health    2.418552e+07
Sports & Fitness     1.613983e+07
Home & Kitchen       1.589259e+07
Books                7.932802e+06
Other                6.209626e+06
Pet Care             4.637088e+06
Toys & Games         4.476831e+06
Name: Net Amount, dtype: float64

In [40]:
df.columns

Index(['CID', 'TID', 'Gender', 'Age Group', 'Purchase Date',
       'Product Category', 'Discount Availed', 'Discount Name',
       'Discount Amount (INR)', 'Gross Amount', 'Net Amount',
       'Purchase Method', 'Location'],
      dtype='object')

In [42]:
df["Purchase Method"].value_counts()

Purchase Method
Credit Card           22096
Debit Card            13809
Net Banking            5485
International Card     2815
Cash on Delivery       2768
PhonePe UPI            2683
Paytm UPI              2674
Google Pay UPI         2670
Name: count, dtype: int64

In [47]:
df.groupby("Purchase Method")["Net Amount"].sum().sort_values(ascending=False)

Purchase Method
Credit Card           6.368935e+07
Debit Card            3.977074e+07
Net Banking           1.576577e+07
International Card    8.045845e+06
PhonePe UPI           7.880951e+06
Cash on Delivery      7.788172e+06
Paytm UPI             7.731004e+06
Google Pay UPI        7.505401e+06
Name: Net Amount, dtype: float64

In [48]:
df.groupby("Purchase Method")["Net Amount"].mean().sort_values(ascending=False)

Purchase Method
PhonePe UPI           2937.365438
Paytm UPI             2891.175723
Credit Card           2882.392929
Debit Card            2880.059595
Net Banking           2874.342454
International Card    2858.204302
Cash on Delivery      2813.646069
Google Pay UPI        2811.011726
Name: Net Amount, dtype: float64

In [54]:
df["Gender"].value_counts()

Gender
Female    18454
Other     18450
Male      18096
Name: count, dtype: int64

In [51]:
df.groupby("Gender")["Net Amount"].sum()

Gender
Female    5.271332e+07
Male      5.190071e+07
Other     5.356321e+07
Name: Net Amount, dtype: float64

In [52]:
df.groupby("Gender")["Net Amount"].mean()

Gender
Female    2856.471115
Male      2868.076360
Other     2903.155111
Name: Net Amount, dtype: float64

In [55]:
df["Age Group"].value_counts()

Age Group
25-45           22010
18-25           16431
45-60           11104
under 18         2771
60 and above     2684
Name: count, dtype: int64

In [56]:
df.groupby("Gender")["Net Amount"].sum()

Gender
Female    5.271332e+07
Male      5.190071e+07
Other     5.356321e+07
Name: Net Amount, dtype: float64

In [57]:
df.groupby("Gender")["Net Amount"].mean()

Gender
Female    2856.471115
Male      2868.076360
Other     2903.155111
Name: Net Amount, dtype: float64

In [59]:
df["Location"].value_counts()

Location
Mumbai       11197
Delhi        10799
Bangalore     8249
Hyderabad     5545
Chennai       4368
Pune          3781
Ahmedabad     2785
Kolkata       2709
Jaipur        1678
Lucknow       1136
Other         1046
Varanasi       606
Dehradun       553
Srinagar       548
Name: count, dtype: int64

In [60]:
df.groupby("Location")["Net Amount"].sum()

Location
Ahmedabad    8.114984e+06
Bangalore    2.361955e+07
Chennai      1.263518e+07
Dehradun     1.569219e+06
Delhi        3.109897e+07
Hyderabad    1.581339e+07
Jaipur       4.854492e+06
Kolkata      7.805355e+06
Lucknow      3.270708e+06
Mumbai       3.208384e+07
Other        3.079422e+06
Pune         1.090214e+07
Srinagar     1.585927e+06
Varanasi     1.744066e+06
Name: Net Amount, dtype: float64

In [61]:
df.groupby("Location")["Net Amount"].mean()

Location
Ahmedabad    2913.818332
Bangalore    2863.322297
Chennai      2892.669814
Dehradun     2837.647190
Delhi        2879.801343
Hyderabad    2851.828002
Jaipur       2893.022720
Kolkata      2881.267840
Lucknow      2879.144477
Mumbai       2865.396180
Other        2943.997920
Pune         2883.400802
Srinagar     2894.026566
Varanasi     2877.996022
Name: Net Amount, dtype: float64

In [66]:
df["Location"].value_counts().size

14

In [69]:
df["Location"].value_counts().sort_values(ascending=False)

Location
Mumbai       11197
Delhi        10799
Bangalore     8249
Hyderabad     5545
Chennai       4368
Pune          3781
Ahmedabad     2785
Kolkata       2709
Jaipur        1678
Lucknow       1136
Other         1046
Varanasi       606
Dehradun       553
Srinagar       548
Name: count, dtype: int64

In [88]:
df["Purchase Date"]=pd.to_datetime(df["Purchase Date"])

In [89]:
df.groupby(df["Purchase Date"].dt.month)["Net Amount"].sum().sort_values(ascending=True)

Purchase Date
2     1.000025e+07
6     1.132360e+07
7     1.184880e+07
1     1.202647e+07
3     1.255316e+07
4     1.301843e+07
5     1.319709e+07
9     1.321861e+07
8     1.321897e+07
10    1.402244e+07
11    1.584837e+07
12    1.790106e+07
Name: Net Amount, dtype: float64

In [94]:
df["Product Category"].value_counts().sort_values(ascending=True)

Product Category
Toys & Games          1529
Pet Care              1618
Other                 2171
Books                 2762
Home & Kitchen        5489
Sports & Fitness      5557
Beauty and Health     8332
Clothing             10968
Electronics          16574
Name: count, dtype: int64

In [97]:
df.groupby("Product Category")["Net Amount"].mean().sort_values(ascending=True)

Product Category
Clothing             2846.496783
Other                2860.260684
Electronics          2864.882810
Pet Care             2865.938000
Books                2872.122383
Home & Kitchen       2895.353235
Beauty and Health    2902.726799
Sports & Fitness     2904.415069
Toys & Games         2927.947260
Name: Net Amount, dtype: float64

In [98]:
df.groupby("Product Category")["Net Amount"].median().sort_values(ascending=True)

Product Category
Pet Care             2751.594800
Other                2772.912450
Clothing             2778.331075
Books                2810.574725
Electronics          2817.571500
Beauty and Health    2824.215712
Toys & Games         2838.360000
Sports & Fitness     2844.427500
Home & Kitchen       2852.518300
Name: Net Amount, dtype: float64

In [ ]:
df.groupby("Purchase Method")["Net Amount"].mean().sort_values(ascending=True)

Purchase Method
Google Pay UPI        2811.011726
Cash on Delivery      2813.646069
International Card    2858.204302
Net Banking           2874.342454
Debit Card            2880.059595
Credit Card           2882.392929
Paytm UPI             2891.175723
PhonePe UPI           2937.365438
Name: Net Amount, dtype: float64

In [103]:
df.groupby("Purchase Method")["Net Amount"].median().sort_values(ascending=True)

Purchase Method
Cash on Delivery      2707.175000
International Card    2771.959900
Google Pay UPI        2785.341688
Paytm UPI             2812.638875
Net Banking           2813.721900
Debit Card            2818.692000
Credit Card           2829.770250
PhonePe UPI           2936.271250
Name: Net Amount, dtype: float64

In [104]:
df["Discount Amount (INR)"].describe()

count    55000.000000
mean       136.986796
std        165.375502
min          0.000000
25%          0.000000
50%          0.000000
75%        274.115000
max        500.000000
Name: Discount Amount (INR), dtype: float64

In [109]:
df.groupby("Product Category")["Discount Amount (INR)"].sum().sort_values(ascending=True)

Product Category
Toys & Games          213281.78
Pet Care              217398.45
Other                 302824.52
Books                 379342.28
Sports & Fitness      752986.20
Home & Kitchen        761206.64
Beauty and Health    1134609.37
Clothing             1511685.72
Electronics          2260938.81
Name: Discount Amount (INR), dtype: float64

In [111]:
df[["Discount Amount (INR)","Gross Amount","Net Amount"]].corr()

                       Discount Amount (INR)  Gross Amount  Net Amount
Discount Amount (INR)               1.000000      0.001473   -0.094341
Gross Amount                        0.001473      1.000000    0.995400
Net Amount                         -0.094341      0.995400    1.000000

In [115]:
df["Gender"].value_counts()

Gender
Female    18454
Other     18450
Male      18096
Name: count, dtype: int64

In [120]:
df.groupby("Gender")["Net Amount"].sum().sort_values(ascending=True)

Gender
Male      5.190071e+07
Female    5.271332e+07
Other     5.356321e+07
Name: Net Amount, dtype: float64

In [121]:
df.groupby("Age Group")["Net Amount"].mean().sort_values(ascending=True)

Age Group
18-25           2848.573795
45-60           2853.368124
60 and above    2886.688814
under 18        2889.693613
25-45           2904.739214
Name: Net Amount, dtype: float64

In [122]:
df["Location"].value_counts().sort_values(ascending=True)

Location
Srinagar       548
Dehradun       553
Varanasi       606
Other         1046
Lucknow       1136
Jaipur        1678
Kolkata       2709
Ahmedabad     2785
Pune          3781
Chennai       4368
Hyderabad     5545
Bangalore     8249
Delhi        10799
Mumbai       11197
Name: count, dtype: int64

In [124]:
df.groupby("Purchase Method")["Net Amount"].sum().sort_values(ascending=True)

Purchase Method
Google Pay UPI        7.505401e+06
Paytm UPI             7.731004e+06
Cash on Delivery      7.788172e+06
PhonePe UPI           7.880951e+06
International Card    8.045845e+06
Net Banking           1.576577e+07
Debit Card            3.977074e+07
Credit Card           6.368935e+07
Name: Net Amount, dtype: float64

In [118]:
df["Age Group"].value_counts()

Age Group
25-45           22010
18-25           16431
45-60           11104
under 18         2771
60 and above     2684
Name: count, dtype: int64

In [119]:
df["Age Group"].value_counts(normalize=True)*100

Age Group
25-45           40.018182
18-25           29.874545
45-60           20.189091
under 18         5.038182
60 and above     4.880000
Name: proportion, dtype: float64